@startuml component-diagram

[Button] #ecec0d
[Subject] #ecec0d
[CourseModal] #ecec0d
[Courses] #ecec0d

[App] --> [Menu]
[App] --> [Subjects]
[App] --> [FullCalendar]
[App] --> [Footer]

[Menu] --> [SubjectAdder]
[Menu] --> [ServerQuery]
[Menu] --> [ImportExport]
[Menu] --> [Settings]
[Menu] --> [Help]
[Menu] --> [Button]

[ServerQuery] --> [Modal]

[Subjects] --> [Subject]

[Subject] --> [Courses]
[Subject] --> [SubjectModal]
[Subject] --> [CourseModal]

@enduml