@startjson state
{
    "settings": {
        "show": {
            "name": true,
            "code": false,
            "time": true,
            "type": false,
            "instructor": true,
            "location": true,
            "notes": false
        },
        "saturday": false,
        "slot": 20,
        "subjectView": "list"
    },
    "currentState": {
        "menu": "Hozzáadás",
        "settings": "show"
    }
}
@endjson