@startjson settings
{
    "show": {
        "code": false,
        "time": true,
        "type": false,
        "instructor": true,
        "location": true,
        "notes": false
    },
    "saturday": false,
    "slot": 20
}
@endjson