@startjson subjects
{
  "id": 1,
  "code": "IP-1234ABCD",
  "name": "Teszt tárgy I.",
  "courses": [
    {
      "id": 1,
      "course": "90",
      "type": "Előadás",
      "instructor": "Példa Béla",
      "location": "2-123",
      "day": "Péntek",
      "startTime": "12:00",
      "endTime": "14:00",
      "notes": "Erasmus kurzus",
      "show": false
    },
    {
      "id": 2,
      "course": "1",
      "type": "Gyakorlat",
      "instructor": "Teszt Dia",
      "location": "1-456",
      "day": "Szerda",
      "startTime": "10:00",
      "endTime": "12:00",
      "notes": "",
      "show": true
    }
  ],
  "status": {
    "color": "#0E2F90",
    "show": true,
    "chosen": {
      "Gyakorlat": 1,
      "Előadás": 90,
      "Egyéb": 0
    }
  }
}
@endjson